let data1 = [
  {
    id: 1,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 2,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 3,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 4,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 5,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 6,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 7,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 8,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 9,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 10,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 11,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 12,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
];

export default data1