let data10 = [
  {
    id: 109,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 110,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 111,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 112,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 113,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 114,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 115,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 116,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 117,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 118,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 119,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 120,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
];

export default data10