export default data11 = [
  {
    id: 121,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 122,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 123,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 124,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 125,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 126,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 127,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 128,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 129,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 130,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 131,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 132,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
];
