export default data4 = [
    {
      id: 37,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 38,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 39,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 40,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 41,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 42,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 43,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 44,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 45,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 46,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 47,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 48,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
  ];
  