let data3 = [
    {
      id: 25,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 26,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 27,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 28,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 29,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 30,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 31,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 32,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 33,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 34,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 35,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 36,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
  ];
  
  export default data3