 let data2 = [
  {
    id: 13,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 14,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 15,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 16,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 17,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 18,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 19,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 20,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 21,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 22,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 23,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 24,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
];

export default data2