let data7 = [
    {
      id: 73,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 74,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 75,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 76,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 77,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 78,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 79,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 80,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 81,
      image: "https://www.linkpicture.com/q/banan_-image.png",
      name: "Banana 1 ct",
      price: 0.69,
      prev_price: null,
      weight: "18 oz",
    },
    {
      id: 82,
      image: "https://www.linkpicture.com/q/strwberry.png",
      name: "Strawberries",
      price: 0.69,
      prev_price: 0.69,
      weight: "1 lb",
    },
    {
      id: 83,
      image: "https://www.linkpicture.com/q/yogert.png",
      name: "Yogurt",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
    {
      id: 84,
      image: "https://www.linkpicture.com/q/berry.png",
      name: "Blackberries",
      price: 0.69,
      prev_price: null,
      weight: "1 lb",
    },
  ];

  export default data7
  