export default data15 = [
  {
    id: 169,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 170,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 171,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 172,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 173,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 174,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 175,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 176,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 177,
    image: "https://www.linkpicture.com/q/banan_-image.png",
    name: "Banana 1 ct",
    price: 0.69,
    prev_price: null,
    weight: "18 oz",
  },
  {
    id: 178,
    image: "https://www.linkpicture.com/q/strwberry.png",
    name: "Strawberries",
    price: 0.69,
    prev_price: 0.69,
    weight: "1 lb",
  },
  {
    id: 179,
    image: "https://www.linkpicture.com/q/yogert.png",
    name: "Yogurt",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
  {
    id: 180,
    image: "https://www.linkpicture.com/q/berry.png",
    name: "Blackberries",
    price: 0.69,
    prev_price: null,
    weight: "1 lb",
  },
];
